version: '3'

services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    container_name: app
    volumes:
      - ./app/:/app
  
  nginx:
    build:
      context: ./web
      dockerfile: ./Dockerfile
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./web/:/var/www
      - ./web/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.conf:/etc/mysql/conf.d/my.conf
      - ./mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    volumes:
      - ./phpmyadmin/sessions:/sessions
    links:
      - db
    ports:
      - 8080:80

networks:
  default:
    name: sampleSNS
    external: true